# Generated by Django 4.2.7 on 2023-12-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0003_alter_pet_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='Height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pet',
            name='Weight',
            field=models.FloatField(default=0),
        ),
    ]
