# Generated by Django 4.2.7 on 2023-12-24 13:46

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0004_pet_height_pet_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200)),
                ('Age', models.IntegerField()),
                ('Address', models.CharField(max_length=500)),
                ('State', models.CharField(max_length=200)),
                ('Pincode', models.IntegerField()),
                ('PhoneNo', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'register',
            },
        ),
        migrations.AlterModelManagers(
            name='pet',
            managers=[
                ('pets', django.db.models.manager.Manager()),
            ],
        ),
    ]
