# Generated by Django 4.2.7 on 2023-12-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0005_register_alter_pet_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='PhoneNo',
            field=models.BigIntegerField(),
        ),
    ]
