# Generated by Django 4.2.7 on 2024-01-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0009_order_payment_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='ordernumber',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
