# Generated by Django 4.2.7 on 2024-01-13 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0010_orderdetails_ordernumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='paymentid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petapp.payment'),
        ),
    ]
