# Generated by Django 4.2.7 on 2024-01-13 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0011_alter_orderdetails_paymentid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order1',
        ),
    ]
